import type Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';

export interface InstallRuntimeResult {
  files_created: number;
  paths: string[];
}

const GODOT_PROJECT = `; Engine configuration file.
; Generated by Game Foundry OS — Studio Bootstrap

[application]

config/name="GameProject"
config/features=PackedStringArray("4.3")
run/main_scene=""

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
`;

const BATTLE_SCENE_GD = `class_name BattleScene
extends Node2D

## ─── REGIONS ─────────────────────────────────────────────
## The battle scene orchestrates encounter flow:
## 1. Load encounter manifest
## 2. Spawn enemy sprites on grid
## 3. Initialize turn order
## 4. Run combat loop
## 5. Handle win/loss conditions

@onready var combat_hud: CombatHud = $CombatHud
@onready var sprite_container: Node2D = $SpriteContainer

var encounter_data: Dictionary = {}
var turn_queue: Array = []
var current_turn_index: int = 0

## ─── LIFECYCLE ───────────────────────────────────────────

func _ready() -> void:
	pass  # Encounter loaded externally via load_encounter()

## ─── ENCOUNTER LOADING ───────────────────────────────────

func load_encounter(manifest_path: String) -> void:
	var loader := EncounterLoader.new()
	encounter_data = loader.load_manifest(manifest_path)
	_spawn_enemies(encounter_data.get("enemies", []))

## ─── SPAWNING ────────────────────────────────────────────

func _spawn_enemies(enemies: Array) -> void:
	for enemy_def in enemies:
		var sprite := SpriteLoader.load_unit_sprite(
			enemy_def.get("sprite_pack", ""),
			enemy_def.get("facing", "front")
		)
		sprite.position = _grid_to_world(
			enemy_def.get("grid_pos", Vector2i.ZERO)
		)
		sprite_container.add_child(sprite)

## ─── GRID ────────────────────────────────────────────────

func _grid_to_world(grid_pos: Vector2i) -> Vector2:
	var cell_size := Vector2(64, 64)
	var offset := Vector2(128, 96)
	return offset + Vector2(grid_pos) * cell_size

## ─── TURN MANAGEMENT ────────────────────────────────────

func advance_turn() -> void:
	current_turn_index = (current_turn_index + 1) % turn_queue.size()

func get_current_unit() -> Dictionary:
	if turn_queue.is_empty():
		return {}
	return turn_queue[current_turn_index]
`;

const COMBAT_HUD_GD = `class_name CombatHud
extends CanvasLayer

## ─── REGIONS ─────────────────────────────────────────────
## The combat HUD provides:
## 1. Turn order display
## 2. Unit status panels (HP, guard, status effects)
## 3. Action menu (attack, skill, item, defend)
## 4. Damage popups and feedback
## 5. Win/loss banners

## ─── PANELS ──────────────────────────────────────────────

func show_turn_order(queue: Array) -> void:
	pass  # Populate turn order bar

func show_unit_status(unit: Dictionary) -> void:
	pass  # Show HP/guard/effects for selected unit

## ─── ACTION MENU ─────────────────────────────────────────

func show_action_menu(actions: Array) -> void:
	pass  # Display available actions for current unit

func hide_action_menu() -> void:
	pass  # Dismiss action panel

## ─── FEEDBACK ────────────────────────────────────────────

func show_damage_popup(target_pos: Vector2, amount: int, is_crit: bool) -> void:
	pass  # Floating damage number

func show_status_effect(unit_id: String, effect: String) -> void:
	pass  # Status icon on unit panel

## ─── BANNERS ─────────────────────────────────────────────

func show_victory() -> void:
	pass  # Victory screen

func show_defeat() -> void:
	pass  # Defeat screen
`;

const SPRITE_LOADER_GD = `class_name SpriteLoader
extends RefCounted

## ─── REGIONS ─────────────────────────────────────────────
## Standard sprite loader for the battle scene.
## Resolves sprite pack paths and creates AnimatedSprite2D nodes.

## Direction mapping: 5 canonical -> 8 runtime
const DIR_MAP := {
	"front": "front",
	"front_34": "front_34",
	"side": "side",
	"back_34": "back_34",
	"back": "back",
	"front_mirror": "front_34",
	"side_mirror": "side",
	"back_mirror": "back_34",
}

static func load_unit_sprite(pack_path: String, facing: String) -> Sprite2D:
	var sprite := Sprite2D.new()
	var resolved_dir := DIR_MAP.get(facing, "front")
	var texture_path := "%s/%s.png" % [pack_path, resolved_dir]

	if ResourceLoader.exists(texture_path):
		sprite.texture = load(texture_path)
	else:
		# Placeholder circle for missing sprites
		sprite.texture = _create_placeholder()

	return sprite

static func _create_placeholder() -> ImageTexture:
	var img := Image.create(48, 48, false, Image.FORMAT_RGBA8)
	img.fill(Color(0.8, 0.2, 0.3, 0.7))
	return ImageTexture.create_from_image(img)
`;

const ENCOUNTER_LOADER_GD = `class_name EncounterLoader
extends RefCounted

## ─── REGIONS ─────────────────────────────────────────────
## Loads encounter manifest JSON files and returns structured
## encounter data for the battle scene.

func load_manifest(manifest_path: String) -> Dictionary:
	if not FileAccess.file_exists(manifest_path):
		push_error("Encounter manifest not found: %s" % manifest_path)
		return {}

	var file := FileAccess.open(manifest_path, FileAccess.READ)
	var json := JSON.new()
	var err := json.parse(file.get_as_text())

	if err != OK:
		push_error("Failed to parse manifest: %s" % json.get_error_message())
		return {}

	var data: Dictionary = json.data
	return _normalize(data)

func _normalize(raw: Dictionary) -> Dictionary:
	var result := {
		"encounter_id": raw.get("encounter_id", ""),
		"display_name": raw.get("display_name", "Unknown"),
		"grid_rows": raw.get("grid_rows", 3),
		"grid_cols": raw.get("grid_cols", 8),
		"enemies": [],
		"rules": raw.get("rules", []),
	}

	for enemy in raw.get("enemies", []):
		result["enemies"].append({
			"display_name": enemy.get("display_name", "Enemy"),
			"variant_id": enemy.get("variant_id", ""),
			"sprite_pack": enemy.get("sprite_pack", ""),
			"grid_pos": Vector2i(
				enemy.get("grid_col", 0),
				enemy.get("grid_row", 0)
			),
			"facing": enemy.get("facing", "front"),
		})

	return result
`;

const PROOF_HARNESS_GD = `extends SceneTree

## ─── PROOF HARNESS ───────────────────────────────────────
## Minimal test runner stub for validating encounter loading
## and sprite resolution at engine runtime.
##
## Run: godot --headless -s tests/proof_harness.gd

func _init() -> void:
	print("=== Game Foundry Proof Harness ===")
	print("Status: shell installed, no tests defined yet")
	print("Add test functions below to validate runtime behavior.")
	quit()
`;

const GD_FILES: Array<{ relative: string; content: string }> = [
  { relative: 'project.godot', content: GODOT_PROJECT },
  { relative: 'battle/scenes/battle_scene.gd', content: BATTLE_SCENE_GD },
  { relative: 'battle/scenes/combat_hud.gd', content: COMBAT_HUD_GD },
  { relative: 'battle/scenes/sprite_loader.gd', content: SPRITE_LOADER_GD },
  { relative: 'battle/scenes/encounter_loader.gd', content: ENCOUNTER_LOADER_GD },
  { relative: 'tests/proof_harness.gd', content: PROOF_HARNESS_GD },
];

const DIRS = [
  'assets/sprites',
  'assets/portraits',
];

export function installRuntimeShell(
  _db: Database.Database,
  _projectId: string,
  godotRoot: string,
): InstallRuntimeResult {
  const paths: string[] = [];

  // Create directories
  for (const dir of DIRS) {
    const fullDir = path.join(godotRoot, dir);
    if (!fs.existsSync(fullDir)) {
      fs.mkdirSync(fullDir, { recursive: true });
    }
  }

  // Write GDScript files
  for (const file of GD_FILES) {
    const fullPath = path.join(godotRoot, file.relative);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(fullPath, file.content, 'utf-8');
    paths.push(fullPath);
  }

  return { files_created: paths.length, paths };
}
